### ISSUE TITLE
I'm making a benchmark tool.Could you add this to your list?

### ISSUE THREAD

**Issue by PenguinCabinet** [cloudmercato/awesome-benchmark#1]
d

**Comment by ZuluPro** [comment]
Hi @PenguinCabinet 
Thank you for your suggestion

Unfortunately as the tool concerns a subject potentialy sensitive accross the different cultures around the world,
I prefer to not include your software

Thank you again

**Comment by PenguinCabinet** [comment]
OK.Thank you for replaying.
